install:
    - sudo apt-get install texlive-latex-base 
    - sudo apt-get install texlive-latex-recommended 
    - sudo apt-get install texlive-fonts-recommended 
    - sudo apt-get install texlive-latex-extra 
    - sudo apt-get install hevea 
    - sudo apt-get install imagemagick 
    - sudo apt-get install texlive-fonts-extra 
    - sudo apt-get install texlive-lang-portuguese 
    - sudo apt-get install texlive-doc-p
script:
    travis.sh
