sudo: false
install:
    - apt-get install -qq texlive-latex-base 
    - apt-get install -qq texlive-latex-recommended 
    - apt-get install -qq texlive-fonts-recommended 
    - apt-get install -qq texlive-latex-extra 
    - apt-get install -qq hevea 
    - apt-get install -qq imagemagick 
    - apt-get install -qq texlive-fonts-extra 
    - apt-get install -qq texlive-lang-portuguese 
    - apt-get install -qq texlive-doc-pt
script:
    ./travis.sh
addons:
  artifacts: true
  s3_region: "us-east-1"
  paths:
    - ./book.pdf

