sudo: false
cache:
    - apt
addons:
  apt:
    sources:
    - extras-precise
    packages:
    - texlive-latex-base 
    - texlive-latex-recommended 
    - texlive-fonts-recommended 
    - texlive-latex-extra 
    - hevea 
    - imagemagick 
    - texlive-fonts-extra 
    - texlive-lang-portuguese 
    - texlive-doc-pt
script:
    ./travis.sh
addons:
  artifacts: true
  s3_region: "us-east-1"
  paths:
    - ./book.pdf

